### ISSUE TITLE
Please help me out running it

### ISSUE THREAD

**Issue by rounakdatta** [lpgauth/flare#12]
How do I run this actually (not the test or benchmark)?  If I type the mentioned in an Erlang shell, errors creep up.
Well, I'm totally a newbie when it comes to Erlang and Kafka. And I've been trying to improve my skills.
Thanks

**Comment by lpgauth** [comment]
Hi @rounakdatta,
What error are you getting? Did you try https://github.com/lpgauth/flare#examples?

**Comment by rounakdatta** [comment]
Yes, when I try the first command on #examples, 
flare_app:start.
Its prompting that the start function is invalid.
What are the prerequisites, like even Kafka and Zookeeper are running.
Do I need to add any environment variables as such, please guide.
Thanks a lot Sir.

**Comment by rounakdatta** [comment]
![error](https://user-images.githubusercontent.com/20105014/30849793-1c2ccd6a-a2c1-11e7-939a-d4b1b45928c2.png)

error sccreenshot

**Comment by lpgauth** [comment]
You might want to learn Erlang first... http://learnyousomeerlang.com

```
cd flare

flare (master)$ make
Running rebar3 compile...
===> Verifying dependencies...
===> Compiling flare

lpgauth flare (master)$ erl -pa _build/default/lib/*/ebin
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.2  (abort with ^G)
1> flare_app:start().
{ok,[granderl,metal,shackle,snappy,flare]}
```

**Comment by rounakdatta** [comment]
Thanks a lot, I was able to run it.
Again, `flare_topic:start(<<"my topic">>, TopicOpts).` throws no_metadata error
![error2](https://user-images.githubusercontent.com/20105014/30865162-7beb4538-a2f3-11e7-88da-31e530db9ce6.png)

**Comment by lpgauth** [comment]
Right, because you don't have a Kafka server running on your localhost... By default it tries to fetch the metadata using `{"127.0.0.1", 9092}`. You need to specify your bootstrap server(s) using the environment variable `broker_bootstrap_servers`.
